### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by liuatgit** [by-syk/UriAnalyser#2]
android 8.1
try to open file from "Downloads" on file manager, the app crashes.

**Comment by liuatgit** [comment]
```
05-22 03:06:12.472 7948-7948/com.by_syk.urianalyser.sample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.by_syk.urianalyser.sample, PID: 7948
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/raw:/storage/emulated/0/Download/sample.jpg flg=0x1 }} to activity {com.by_syk.urianalyser.sample/com.by_syk.urianalyser.sample.MainActivity}: java.lang.NumberFormatException: For input string: "raw:/storage/emulated/0/Download/sample.jpg"
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4268)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4312)
        at android.app.ActivityThread.-wrap19(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1644)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NumberFormatException: For input string: "raw:/storage/emulated/0/Download/sample.jpg"
        at java.lang.Long.parseLong(Long.java:590)
        at java.lang.Long.valueOf(Long.java:804)
        at com.by_syk.lib.urianalyser.UriAnalyser.getRealPathFromDocumentUri(UriAnalyser.java:240)
        at com.by_syk.lib.urianalyser.UriAnalyser.getRealPath(UriAnalyser.java:144)
        at com.by_syk.urianalyser.sample.MainActivity.onActivityResult(MainActivity.java:70)
        at android.app.Activity.dispatchActivityResult(Activity.java:7276)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4264)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4312) 
        at android.app.ActivityThread.-wrap19(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1644) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
05-22 03:06:12.477 1680-2576/system_process W/ActivityManager:   Force finishing activity com.by_syk.urianalyser.sample/.MainActivity
05-22 03:06:12.483 1680-1696/system_process I/ActivityManager: Showing crash dialog for package com.by_syk.urianalyser.sample u0
```
